# Generated by Django 3.1.7 on 2021-03-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.BooleanField(default=False)),
                ('part_time', models.BooleanField(default=False)),
                ('temporary', models.BooleanField(default=False)),
                ('contract', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('seasonal', models.BooleanField(default=False)),
                ('co_founder', models.BooleanField(default=False)),
                ('freelance', models.BooleanField(default=False)),
                ('per_diem', models.BooleanField(default=False)),
                ('reserve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('working_here', models.BooleanField(default=False)),
                ('date_started', models.DateField(null=True)),
                ('date_ended', models.DateField(null=True)),
                ('skills_used', models.CharField(blank=True, max_length=300, null=True)),
                ('describe_accomplishment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='steps.jobtitle')),
                ('opportunity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='steps.opportunityavailable')),
                ('work_experience', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='steps.workexperience')),
            ],
        ),
    ]
